server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001   #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service  #通过微服务名称动态访问  lb是load balance的缩写
          predicates:
            - Path=/payment/select/**   #断言,路径相匹配的进行路由
            - After=2021-03-06T10:59:34.102+08:00[Asia/Shanghai]  #这个时间之后可以访问
            - Between=2021-03-06T10:59:34.102+08:00[Asia/Shanghai] ,  2022-03-08T10:59:34.102+08:00[Asia/Shanghai]
            - Header=X-Request-Id, \d+   #请求头中要有X-Request-Id属性并且值为整数的正则表达式
            #- Host=**.baidu.com
            #- Method=GET
            #- Query=username, \d+ #要有参数名称并且是正整数才能路由
          #filters:
            #- AddRequestParameter=X-Request-Id,1024 #过滤工厂毁在匹配的请求头加上一对请求头，名称为X-Request-Id,值为1024


        - id: payment_routh2
          #uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/port/**   #断言,路径相匹配的进行路由
    loadbalancer:
      ribbon:
        enabled: false


eureka:
  instance:
    hostname: cloud-gateway-service
    prefer-ip-address: true
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka
