server:
  port: 8088

spring:
  application:
    name: cloud-order-feign-feignclient

eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      #      defaultZone: http://localhost:7001/eureka   #单个发版
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/  #发布到集群eureka中
  instance:
    instance-id: order-feign-8088   #修改注册进eureka中(status)实例的显示名称,当前电脑默认显示：LAPTOP-RT5PR5EG:cloud-Payment-feignclient:8001
    prefer-ip-address: true    #鼠标移动到payment8001链接名称上，左下角显示Ip+端口的形式
#设置feign客户端超时时间（Openfeign默认是支持Ribbon）
ribbon:
  #指建立连接所用的时间，适用于网络状况正常的情况下。两端连接所用的时间
  ReadTimeout:  5000
  #指建立服务连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000

#日志级别
logging:
  level:
    com.cloud.service.PaymentFeignService: debug  #指定接口级别